build: off

test_script:
- echo "aaa" | cat
- echo aa^
    
    aa | cat
- echo aa^
    
    aa^
    y | cat
- echo "a\naa" | cat
- echo -en "123\\ny\\nn\\n" | cat
- cmd: echo "cmd aaa" | cat
- cmd: echo -en "cmd 123\\ny\\nn\\n" | cat
- ps: Write-Host "ps aaa" | Get-Content
- ps: Write-Host "ps 123`ny`nn`n" | Get-Content
- echo --help
- echo /?
- cmd: echo /?
- ps: echo -help
